package com.model;

/**
 * TCatelog generated by MyEclipse Persistence Tools
 */

public class TCatelog implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String name;

	private String jieshao;

	private String del;

	// Constructors

	/** default constructor */
	public TCatelog()
	{
	}

	/** full constructor */
	public TCatelog(String name, String jieshao, String del)
	{
		this.name = name;
		this.jieshao = jieshao;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getJieshao()
	{
		return this.jieshao;
	}

	public void setJieshao(String jieshao)
	{
		this.jieshao = jieshao;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}