package com.model;

/**
 * TChukuMingxi generated by MyEclipse Persistence Tools
 */

public class TChukuMingxi implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer chuku_id;

	private Integer goods_id;

	private Integer shuliang;

	private String beizhu;
	
	private String goods_name;

	// Constructors

	/** default constructor */
	public TChukuMingxi()
	{
	}


	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}


	public String getGoods_name()
	{
		return goods_name;
	}


	public void setGoods_name(String goods_name)
	{
		this.goods_name = goods_name;
	}


	public Integer getChuku_id()
	{
		return chuku_id;
	}


	public void setChuku_id(Integer chuku_id)
	{
		this.chuku_id = chuku_id;
	}


	public Integer getGoods_id()
	{
		return goods_id;
	}


	public void setGoods_id(Integer goods_id)
	{
		this.goods_id = goods_id;
	}


	public Integer getShuliang()
	{
		return this.shuliang;
	}

	public void setShuliang(Integer shuliang)
	{
		this.shuliang = shuliang;
	}

	public String getBeizhu()
	{
		return this.beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

}