package com.model;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class TGoods implements java.io.Serializable
{

	// Fields

	private Integer id;
	private Integer catelog_id;
	private String name;
	private String chandi;

	private String danwei;
	private String guige;
	private String beizhu;
	private String del;

	// Constructors

	/** default constructor */
	public TGoods()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}


	public Integer getCatelog_id()
	{
		return catelog_id;
	}


	public void setCatelog_id(Integer catelog_id)
	{
		this.catelog_id = catelog_id;
	}


	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getChandi()
	{
		return this.chandi;
	}

	public void setChandi(String chandi)
	{
		this.chandi = chandi;
	}

	public String getDanwei()
	{
		return this.danwei;
	}

	public void setDanwei(String danwei)
	{
		this.danwei = danwei;
	}

	public String getGuige()
	{
		return this.guige;
	}

	public void setGuige(String guige)
	{
		this.guige = guige;
	}

	public String getBeizhu()
	{
		return this.beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}