package com.model;

/**
 * TKucun generated by MyEclipse Persistence Tools
 */

public class TKucun implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer goods_id;

	private Integer shuliang;
	
	private String goods_name;

	// Constructors

	/** default constructor */
	public TKucun()
	{
	}


	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}


	public Integer getGoods_id()
	{
		return goods_id;
	}


	public void setGoods_id(Integer goods_id)
	{
		this.goods_id = goods_id;
	}


	public String getGoods_name()
	{
		return goods_name;
	}


	public void setGoods_name(String goods_name)
	{
		this.goods_name = goods_name;
	}


	public Integer getShuliang()
	{
		return this.shuliang;
	}

	public void setShuliang(Integer shuliang)
	{
		this.shuliang = shuliang;
	}

}