package com.model;

/**
 * TRuku generated by MyEclipse Persistence Tools
 */

public class TRuku implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String danjuhao;

	private String shijian;

	private Integer zongjiage;

	private String jingshouren;

	private String beizhu;

	private String del;
	
	private String lb;

	// Constructors

	/** default constructor */
	public TRuku()
	{
	}

	/** full constructor */
	public TRuku(String danjuhao, String shijian, Integer zongjiage,
			String jingshouren, String beizhu, String del,String lb)
	{
		this.danjuhao = danjuhao;
		this.shijian = shijian;
		this.zongjiage = zongjiage;
		this.jingshouren = jingshouren;
		this.beizhu = beizhu;
		this.del = del;
		this.lb = lb;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getDanjuhao()
	{
		return this.danjuhao;
	}

	public void setDanjuhao(String danjuhao)
	{
		this.danjuhao = danjuhao;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public Integer getZongjiage()
	{
		return this.zongjiage;
	}

	public void setZongjiage(Integer zongjiage)
	{
		this.zongjiage = zongjiage;
	}

	public String getJingshouren()
	{
		return this.jingshouren;
	}

	public void setJingshouren(String jingshouren)
	{
		this.jingshouren = jingshouren;
	}

	public String getBeizhu()
	{
		return this.beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}
	
	public String getLb()
	{
		return this.lb;
	}

	public void setLb(String lb)
	{
		this.lb = lb;
	}

}